apiVersion: v1
kind: Pod
metadata: 
  # name of the object. here Pod
  name: nginx
  namespace: default
spec: 
  containers: 
    - name: nginx
      image: nginx:1.14.2
      ports: 
      - containerPort: 80


